/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import Controller.KetNoiCSDL;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logInorSignIn.homeFrame;

/**
 *
 * @author Thanh Diệp
 */

public class Dictionary1 extends javax.swing.JFrame {

    /**
     * Creates new form Dictionary1
     */
    
    public Dictionary1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_input = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_Search = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        scroll_search = new javax.swing.JScrollPane();
        txt_search = new javax.swing.JTextArea();
        btn_Speak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEARCH WORDS");
        setBackground(new java.awt.Color(51, 51, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        txt_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_inputMouseClicked(evt);
            }
        });

        btn_add.setIcon(new javax.swing.ImageIcon("D:\\My Study\\JAVA\\NETBEANS\\Dictionary\\images\\add.png")); // NOI18N
        btn_add.setToolTipText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_exit.setIcon(new javax.swing.ImageIcon("D:\\My Study\\JAVA\\NETBEANS\\Dictionary\\images\\shut_down.png")); // NOI18N
        btn_exit.setToolTipText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Search.setIcon(new javax.swing.ImageIcon("D:\\My Study\\JAVA\\NETBEANS\\Dictionary\\images\\search_user.png")); // NOI18N
        btn_Search.setText("Search");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });
        btn_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_SearchKeyPressed(evt);
            }
        });

        btn_refresh.setIcon(new javax.swing.ImageIcon("D:\\My Study\\JAVA\\NETBEANS\\Dictionary\\images\\refresh.png")); // NOI18N
        btn_refresh.setToolTipText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_home.setBackground(new java.awt.Color(51, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon("D:\\My Study\\JAVA\\NETBEANS\\Dictionary\\images\\home.png")); // NOI18N
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add)
                    .addComponent(btn_refresh)
                    .addComponent(btn_exit)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_home)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scroll_search.setBackground(new java.awt.Color(51, 51, 51));

        txt_search.setBackground(new java.awt.Color(204, 204, 204));
        txt_search.setColumns(20);
        txt_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_search.setRows(5);
        scroll_search.setViewportView(txt_search);

        btn_Speak.setIcon(new javax.swing.ImageIcon("D:\\My Study\\JAVA\\NETBEANS\\Dictionary\\images\\sound_low.png")); // NOI18N
        btn_Speak.setToolTipText("Speaker");
        btn_Speak.setActionCommand("");
        btn_Speak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SpeakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scroll_search, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_Speak, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Speak, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_search, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        // TODO add your handling code here:
        ArrayList<Words> list = new ArrayList<Words>();

        list = KetNoiCSDL.findWord(txt_input.getText());
        // showAble(); // show all data
        boolean f = true;
        for (Words w : list) {
            if (w.getWord().equalsIgnoreCase(txt_input.getText())) {
                txt_search.setText(null);
                txt_search.append(w.getWord());
                txt_search.append("\n");
                txt_search.append(w.getMean());
                txt_search.append("\n");
                txt_search.append(w.getExample());
                txt_search.append("\n");

                f = false;
            }
        }

        if (f) {
            int opt = JOptionPane.showConfirmDialog(btn_Search, "No this word in Dictionary! \nDo you want to insert it into your Dictionary?",
                            "Message", JOptionPane.YES_NO_OPTION);
            if (opt == 0) {
                AddWord adds = new AddWord();
                adds.setVisible(true);
                adds.txt_word.setText(txt_input.getText());
                
                dispose();
            }
        }
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        homeFrame home = new homeFrame();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        txt_search.setText(null);
	txt_input.setText(null);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        AddWord adds = new AddWord();
        adds.setVisible(true);
        adds.txt_word.setText(txt_input.getText());
        dispose();
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(btn_exit, "Are you sure " + "to exit?", "Warning",
			JOptionPane.WARNING_MESSAGE);
	if (opt == 0)
            System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_SpeakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SpeakActionPerformed
        // TODO add your handling code here:
        System.setProperty("freetts.voices", "de.dfki.lt.freetts.en.us.MbrolaVoiceDirectory");
        System.setProperty("mbrola.base", "D:\\My Study\\JAVA\\BTL_JAVA\\JAVA_speech\\mbrola");
        VoiceManager vm = VoiceManager.getInstance();
        Voice voice = vm.getVoice("mbrola_us1");
        try {
            voice.allocate();
            if(txt_input.getText().length()<=0)
                voice.speak("Can't read, please check again!");
            else
                voice.speak(txt_input.getText());
            
            voice.deallocate();
        } catch (Exception e) {
            voice.speak("Failed! Please check again!");
        }
    }//GEN-LAST:event_btn_SpeakActionPerformed

    private void txt_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_inputMouseClicked
        // TODO add your handling code here:
        txt_input.setText("");
    }//GEN-LAST:event_txt_inputMouseClicked

    private void btn_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_SearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionary1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionary1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionary1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionary1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dictionary1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_Speak;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scroll_search;
    private javax.swing.JTextField txt_input;
    private javax.swing.JTextArea txt_search;
    // End of variables declaration//GEN-END:variables
}
